export const ActionTypes = {
  FETCH_PHOTOS_FOR_USER: 'FETCH_PHOTOS_FOR_USER',
  SELECT_PHOTO: 'SELECT_PHOTO',
  AUTHENTICATE: 'AUTHENTICATE'
}

export const AsyncActionStages = {
  BEGIN: 'BEGIN',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR'
}
